name: scanpackage
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.6+9

environment:
  sdk: ">=3.4.0-282.2.beta <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_barcode_scanner: ^2.0.0
  crypto: ^3.0.3
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  toastification: ^2.3.0
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  timezone: ^0.9.4
  connectivity_plus: ^6.1.0
  lottie: ^3.1.2
  persistent_bottom_nav_bar: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
